### ISSUE TITLE
Метод containsGame в классе GameStore всегда возвращает false

### ISSUE THREAD

**Issue by Romagor** [Romagor/Team-project#1]
# **Описание**
Метод containsGame в классе GameStore не находит игру и возвращает значение false, после добавления игры в Store

# **Локация дефекта**
https://github.com/Romagor/Team-project/blob/8820acb5ccf315d58006eaecdbdc55e3e8f2b66c/src/main/java/ru/netology/GameStore.java#L32-L36

# **Шаги воспроизведения**

1. Открыть [код программы/ветка gamestore](https://github.com/Romagor/Team-project/tree/gamestore) в IDEA
2. Запустить тест shouldAddGame из класса [GameStoreTest](https://github.com/Romagor/Team-project/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java)
3. Проверить вывод на консоли

_Ожидаемый результат_: Тест проходит. Результат теста true
_Фактический результат_: Тест не проходит. Результат теста false. Сообщение в консоли о несоответствии ожидаемого результата фактическому

# **Скриншот**
![Снимок экрана 2022-08-11 122554](https://user-images.githubusercontent.com/103060276/184103789-8e7d5956-765a-4e42-abc4-6c6bd4db61b0.png)

# **Окружение**

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
- JAVA: OpenJDK 11.0.15

**Comment by Marina1977D** [comment]
# Внесены поправки в код
  public boolean containsGame(Game game) {
        for (int i = 0; i < games.size(); i++) {
            if (games.get(i).equals(game)) {
                return true;
            }
        }
        return false;
# Скриншот
![image](https://skr.sh/i/160822/cRlt0eNM.jpg?download=1&name=Скриншот%2016-08-2022%2007:50:30.jpg)
