### ISSUE TITLE
К коллекции playedTime нет доступа.

### ISSUE THREAD

**Issue by Marina1977D** [Romagor/Team-project#10]
# Описание. 
Невозможно обратиться к коллекции playedTime в классе Player.

# Локация дефекта.
https://github.com/Romagor/Team-project/blob/41c61913395e095f4f467eb34d4b01ebedf5f3c6/src/main/java/ru/netology/Player.java#L14

# Шаги воспроизведения
1. Открыть[код программы](https://github.com/Romagor/Team-project/blob/41c61913395e095f4f467eb34d4b01ebedf5f3c6/src/test/java/ru/netology/PlayerTest.java#L133-L144) в IDEA.
1.  Запустить тест shouldInstallNewGame.
1.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Тест проходит, ошибок нет.
*Фактический результат:* Тест не проходит. Сообщение в консоли: java: playedTime has private access in ru.netology.Player.

# Скриншот
![image](https://skr.sh/i/210822/GKiNTuKR.jpg?download=1&name=Скриншот%2021-08-2022%2012:30:23.jpg)

# Окружение.
* **Операционная система:** Windows 11 Pro
* **IDEA:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:**  11 Eclipce Temurin cersion 11.0.14

**Comment by Romagor** [comment]
Исправлен модификатор доступа
![Снимок экрана 2022-08-21 131234](https://user-images.githubusercontent.com/103060276/185786213-ee3ec4bb-de84-48b8-a9f7-ad96a7f98626.png)
Тест проходит
![Снимок экрана 2022-08-21 131341](https://user-images.githubusercontent.com/103060276/185786244-52a56013-11db-4f84-be28-aecb5addd30b.png)
