### ISSUE TITLE
Метод public int sumGenre(String genre) не суммирует время игр

### ISSUE THREAD

**Issue by Marina1977D** [Romagor/Team-project#2]
# Описание
Метод public int sumGenre(String genre) не суммирует время игр

# Локализация дефекта
https://github.com/Romagor/Team-project/blob/8820acb5ccf315d58006eaecdbdc55e3e8f2b66c/src/main/java/ru/netology/Player.java#L45
org.opentest4j.AssertionFailedError:
Expected :3
Actual :0
# Шаги воспроизведения
1.Запустить [тест](https://github.com/Romagor/Team-project/blob/93c966977ef481e8749ba1e58de850f8ac93e153/src/test/java/ru/netology/PlayerTest.java#L9-L20)

# Скриншот
![image](https://skr.sh/i/120822/jg2YOri0.jpg?download=1&name=Скриншот%2012-08-2022%2009:37:02.jpg)
 
# Окружение
* **Операционная система:**  Windows 11 Pro
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** 11 Eclipce Temurin cersion 11.0.14

**Comment by Romagor** [comment]
Исправлен код в методе sumGenre
![Снимок экрана 2022-08-16 114300](https://user-images.githubusercontent.com/103060276/184837120-926c9823-c0c8-4b91-9801-c11da5ce3ad6.png)
