### ISSUE TITLE
Метод getMostPlayer, в классе Gamestore, не принимает значение времени равное 1

### ISSUE THREAD

**Issue by Romagor** [Romagor/Team-project#3]
# **Описание**

 В классе Gamestore метод getMostPlayer, не принимает значение времени равное 1

# **Локализация**

https://github.com/Romagor/Team-project/blob/8820acb5ccf315d58006eaecdbdc55e3e8f2b66c/src/main/java/ru/netology/GameStore.java#L58-L69

# **Шаги воспроизведения**

1. Открыть [код программы/ветку gamestore](https://github.com/Romagor/Team-project/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Запустить тест shouldGetMostPlayerEquallyOne
3. Проверить вывод в консоли

_Ожидаемый результат:_ Тест проходит. Результат теста -  метод getMostPlayer вернул значение имени игрока "Пётр", время добавилось
_Фактический результат:_ Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата фактическому

# **Скриншот**
![Снимок экрана 2022-08-13 115232](https://user-images.githubusercontent.com/103060276/184476578-e9aa59c7-c2c7-4eac-bff6-ac7486f54e7a.png)

# **Окружение**

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
- JAVA: OpenJDK 11.0.15

**Comment by Marina1977D** [comment]
![image](https://skr.sh/i/170822/sX8dN85T.jpg?download=1&name=Скриншот%2017-08-2022%2016:14:52.jpg)
