### ISSUE TITLE
Метод SumGenre не суммирует время нескольких игр в каталоге.

### ISSUE THREAD

**Issue by Marina1977D** [Romagor/Team-project#4]
# Описание
Метод SumGenre не суммирует время игр при наличии нескольких игр в каталоге.

# Локация дефекта
https://github.com/Romagor/Team-project/blob/93c966977ef481e8749ba1e58de850f8ac93e153/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Romagor/Team-project/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить [тест](https://github.com/Romagor/Team-project/blob/93c966977ef481e8749ba1e58de850f8ac93e153/src/test/java/ru/netology/PlayerTest.java#L24-L43)
1. Посмотреть на вывод результата в консоли
*Ожидаемый результат:* 3
*Фактический результат:* 0

# Скриншот
![image](https://skr.sh/i/150822/4xNRGSKL.jpg?download=1&name=Скриншот%2015-08-2022%2008:42:44.jpg)

# Окружение
* **Операционная система:** Windows 11 Pro
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** 11 Eclipce Temurin cersion 11.0.14

**Comment by Romagor** [comment]
Метод sumGenere не суммировал время нескольких игр, т.к. была ошибка в коде метода play, метод возвращал суммарное количество часов, проигранное в игру. Внесены изменения в коде методов sumGenere и play.
![Снимок экрана 2022-08-16 114300](https://user-images.githubusercontent.com/103060276/184840126-442c22ab-cac2-4234-8658-c267c91ca5a2.png)
![Снимок экрана 2022-08-16 115352](https://user-images.githubusercontent.com/103060276/184840130-3957179c-d2c1-4c87-b37d-bd143ce13759.png)
