### ISSUE TITLE
В тесте TestSumGenreTwoGames, класса PlayerTest неверно указан ожидаемый результат. Тест не проходит

### ISSUE THREAD

**Issue by Romagor** [Romagor/Team-project#5]
# **Описание**
В тесте TestSumGenreTwoGames, класса PlayerTest неверно указан ожидаемый результат - expected = 3, хотя исходя из параметров теста ожидаемый результат должен быть expected = 6. Тест не проходит.

# **Локализация дефекта**
https://github.com/Romagor/Team-project/blob/02da71456fc3db548fadaecb207cc3dae9d0a3d0/src/test/java/ru/netology/PlayerTest.java#L24-L43

# **Шаги воспроизведения**

1. Открыть [код программы / ветку player](https://github.com/Romagor/Team-project/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить тест TestSumGenreTwoGames в классе PlayerTest
3. Посмотреть на вывод в консоли

_Ожидаемый результат:_ Тест проходит.
_Фактический результат:_ Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата фактическому

# **Скриншот**
![Снимок экрана 2022-08-16 174007](https://user-images.githubusercontent.com/103060276/184907919-7be920c7-e826-4332-801e-4fc2842d347e.png)

# **Окружение**

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
- JAVA: OpenJDK 11.0.15

**Comment by Marina1977D** [comment]
amendments have been made
![image](https://skr.sh/i/170822/5rvhExok.jpg?download=1&name=Скриншот%2017-08-2022%2008:45:36.jpg)
