### ISSUE TITLE
Метод public int play не выдает RunTimeExeption.

### ISSUE THREAD

**Issue by Marina1977D** [Romagor/Team-project#6]
# Описание.
Вызов  к неустановленной игре не выдает RunTimeExeption в методе public int play(Game game, int hours).

# Локация дефекта.
https://github.com/Romagor/Team-project/blob/79a10ed2fc383361ad73f4e636bc9151970461bb/src/main/java/ru/netology/Player.java#L39-L47

# Шаги воспроизведения.
1. Открыть [код программы](https://github.com/Romagor/Team-project/blob/player/src/test/java/ru/netology/PlayerTest.java#L65) в IDEA.
1. Запустить [тест](https://github.com/Romagor/Team-project/blob/4380ab7686dcbffdb8ba5f6ef0baf6684f781894/src/test/java/ru/netology/PlayerTest.java#L65).
1. Посмотреть на результат в консоли.

*Ожидаемый результат:* Выводится ошибка "RuntimeException"
*Фактический результат:* org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот.
![image](https://skr.sh/i/170822/MDlQFXtS.jpg?download=1&name=Скриншот%2017-08-2022%2017:30:40.jpg)

# Окружение.
* **Операционная система:**  Windows 11 Pro
* **IDE:**  IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** 11 Eclipce Temurin cersion 11.0.14

**Comment by Romagor** [comment]
Исправлен код метода play
![Снимок экрана 2022-08-18 121842](https://user-images.githubusercontent.com/103060276/185359585-b83bcc8b-9e90-4d92-b5ed-fabbd1054c8e.png)
Тест проходит
![Снимок экрана 2022-08-18 121925](https://user-images.githubusercontent.com/103060276/185359685-f2a79cf0-c384-4a1e-8910-85e8652b4cd1.png)
