### ISSUE TITLE
Метод mostPlayerByGenre возвращает null при установленных играх

### ISSUE THREAD

**Issue by Marina1977D** [Romagor/Team-project#7]
# Описание.
Метод mostPlayerByGenre(String genre) при наличии установленных игр всегда возвращает null. Не выдавая жанр игры.

# Локация дефекта.
https://github.com/Romagor/Team-project/blob/4380ab7686dcbffdb8ba5f6ef0baf6684f781894/src/main/java/ru/netology/Player.java#L67-L68

# Шаги воспроизведения.
1. Открыть [код программы](https://github.com/Romagor/Team-project/blob/player/src/main/java/ru/netology/Player.java#L67-L68)
1. Запустит [тест]( https://github.com/Romagor/Team-project/blob/player/src/test/java/ru/netology/PlayerTest.java#L81-L99)
1. Посмотреть на результат теста в консоли.

*Ожидаемый результат:*   Call of Duty
*Фактический результат:*  null

# Скриншот.
![image]( https://skr.sh/i/180822/DT62z1Lf.jpg?download=1&name=Скриншот%2018-08-2022%2008:05:02.jpg)

# Окружение. 

* **Операционная система:**  Windows 11 Pro
* **IDE:** IntelliJ IDEA 2022.1 (Community Edition)
* **Java:** 11 Eclipce Temurin cersion 11.0.14

**Comment by Romagor** [comment]
Добавлен необходимый код в методе mostPlayerByGenre
![Снимок экрана 2022-08-18 160803](https://user-images.githubusercontent.com/103060276/185402581-5ed115fb-f52a-4ed5-b468-54beb99738c3.png)
Также внесено изменение в строке 97 теста shouldMostPlayerByGenre
![Снимок экрана 2022-08-18 161005](https://user-images.githubusercontent.com/103060276/185402950-e8c12827-483f-43cd-9a25-96db0de4e0bd.png)
