### ISSUE TITLE
Метод getSumPlayedTime в классе GameStore не возвращает сумму времени всех игроков

### ISSUE THREAD

**Issue by Romagor** [Romagor/Team-project#9]
# **Описание**
Метод getSumPlayedTime в классе GameStore не возвращает сумму времени всех игроков, а возвращает ноль

# **Локализация дефекта**
https://github.com/Romagor/Team-project/blob/3b10fd21f0bd1689b7eb838483339ca3bd1603ad/src/main/java/ru/netology/GameStore.java#L75-L77

# **Шаги воспроизведения**

1. Открыть [код программы/ветку gamestore](https://github.com/Romagor/Team-project/tree/gamestore)
2. Запустить тест shouldGetSumPlayedTime в классе GameStoreTest
3. Проверить вывод на консоли

_Ожидаемый результат:_ Тест проходит. Время суммировалось, метод getSumPlayedTime вернул верное значение - 7
_Фактический результат_ Тест не проходит. Метод getSumPlayedTime возвращает неверное значение - 0

_Дополнительно:_ По той же причине не проходит тест shouldGetSumOnePlayedTime

# **Скриншот**
![Снимок экрана 2022-08-18 172905](https://user-images.githubusercontent.com/103060276/185420433-0707a53f-5e3d-4ead-a22a-904f4ea7d092.png)

# **Окружение**

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
- JAVA: OpenJDK 11.0.15

**Comment by Marina1977D** [comment]
amendments have been made, the error has been closed
![image](https://skr.sh/i/190822/XTWBhsIs.jpg?download=1&name=Скриншот%2019-08-2022%2008:30:20.jpg)
